export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";

export const REFRESH_PRODUCT_LIST = "REFRESH_PRODUCT_LIST";
export const REFRESH_CONTACT_LIST = "REFRESH_CONTACT_LIST";

export const REFRESH_INVOICE_LIST = "REFRESH_INVOICE_LIST";

export const REFRESH_PAY_METHOD_LIST = "REFRESH_PAY_METHOD_LIST";

export const REFRESH_PAYMENT_LIST = "REFRESH_PAYMENT_LIST";

export const REFRESH_LOCATION_LIST = "REFRESH_LOCATION_LIST";

export const REFRESH_GR_LIST = "REFRESH_GR_LIST";

export const REFRESH_GI_LIST = "REFRESH_GI_LIST";

